parameters:
    ngld.assetic.lessc.compress: true
    ngld.assetic.lessc.ie_compat: false
    ngld.assetic.lessc.source_map: true

services:
    ngld.assetic.lessc:
        class: Ngld\AsseticBundle\Filter\LesscFilter
        calls:
            - [setCompress, ['%ngld.assetic.lessc.compress%']]
            - [setIeCompat, ['%ngld.assetic.lessc.ie_compat%']]
            - [setSourceMap, ['%ngld.assetic.lessc.source_map%']]
        tags:
            - { name: assetic.filter, alias: lessc }
